<a id='top'></a>

# CSCI 3022: Intro to Data Science - Fall 2019 Practicum 2
***

This practicum is due on Canvas by **11:59 PM on Wednesday December 11**. Your solutions to theoretical questions should be done in Markdown/MathJax directly below the associated question.  Your solutions to computational questions should include any specified Python code and results as well as written commentary on your conclusions.  

**Here are the rules:** 

1. All work, code and analysis, must be your own. 
1. You may use your course notes, posted lecture slides, textbooks, in-class notebooks, and homework solutions as resources.  You may also search online for answers to general knowledge questions like the form of a probability distribution function or how to perform a particular operation in Python/Pandas. 
1. This is meant to be like a coding portion of your midterm exam. So, the instructional team will be much less helpful than we typically are with homework. For example, we will not check answers, help debug your code, and so on.
1. If something is left open-ended, it is because we want to see how you approach the kinds of problems you will encounter in the wild, where it will not always be clear what sort of tests/methods should be applied. Feel free to ask clarifying questions though.
2. You may **NOT** post to message boards or other online resources asking for help.
3. You may **NOT** copy-paste solutions *from anywhere*.
4. You may **NOT** collaborate with classmates or anyone else.
5. In short, **your work must be your own**. It really is that simple.

Violation of the above rules will result in an immediate academic sanction (*at the very least*, you will receive a 0 on this practicum or an F in the course, depending on severity), and a trip to the Honor Code Council.

**By submitting this assignment, you agree to abide by the rules given above.**

***

**Name**: Abigail Nay 

***


**NOTES**: 

- You may not use late days on the practicums nor can you drop your practicum grades. 
- If you have a question for us, post it as a **PRIVATE** message on Piazza.  If we decide that the question is appropriate for the entire class, then we will add it to a Practicum clarifications thread. 
- Do **NOT** load or use any Python packages that are not available in Anaconda 3.6. 
- Some problems with code may be autograded.  If we provide a function API **do not** change it.  If we do not provide a function API then you're free to structure your code however you like. 
- Submit only this Jupyter notebook to Canvas.  Do not compress it using tar, rar, zip, etc. 
- This should go without saying, but... For any question that asks you to calculate something, you **must show all work to receive credit**. Sparse or nonexistent work will receive sparse or nonexistent credit.

---
**Shortcuts:**  [Problem 1](#p1) | [Problem 2](#p2) | [Bottom](#bot)

---

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

from calendar import month_name, different_locale
from scipy import stats
from scipy.stats import t
import statsmodels.api as sm
from scipy.special import binom
import math
import random
from random import sample
from random import choices

<br>

---
<a id='p1'></a>
[Back to top](#top)

### [40 points] Problem 1:  Amazon Forest Fires

A non-profit orgranization is trying to protect the Amazon rain forest and has recruited you as their head data scientist. For your first task, they've given you a dataset with the number of fires in each state in the Amazon region during each month between 1998 and 2017. They would like to have a 95% confidence interval for the true median number of forest fires that occur in each state on a yearly basis.

In [ ]:
#Starter Code
df = pd.read_csv('amazon.csv', thousands='.', decimal ='/', engine='python')
df.info()

**Part A:**  This dataset isn't paticularly useful in it's current state, so we'll need to clean it up a bit. Some data scientists say that most of their job is to wrangle data, so this will give you a taste of cleaning a real world data set. Perform the following tasks:
1. Drop the 'date' column. The only information this column holds is the year, which we already have in another column. 
2. Drop any rows with null values in any of the remaining columns
3. Print all the unique values of the 'month' column. You'll notice that one is encoded with a differant character encoding then the format that pandas is using.
3. Convert the Portugese month names to English month names. We've included the 'month_name' and the 'different_encoding' modules of the python calendar library in the top cell above, if you would like to use them. There are many ways to accomplish this task, and these modules are not required, but may make things easier. As part of this step, you should make sure that the Portugese month with the encoding problem is translated to the correct English month. 
4. Check the number column for any values that seem impossible. Drop any negative or fractional values, or any values over 50,000. 50,000 is large enough that no Brazilian state would ever have that many forest fires in one month, so we should get rid of anything above 50000. 
5. Since you're new on the job, some of your co-workers may have played a prank on you... Print out all the unique values of the 'year' column and drop any rows with values that don't make sense.
6. Find the total number of rows remaining after you've done all of the above and write it out in a markdown cell. if you have correctly performed all of the tasks above, your dataframe should now have 6438 rows.

**NOTE:** Since some of these tasks are not totally trivial, you may use any resources other than your classmates on this part of this problem. This means you may consult google, stack overflow, the python/pandas documentation, some random book on pandas you might have, etc... But you may not consult your classmates for help. ***CITE ALL RESOURCES USED IN A CODE COMMENT. A URL OR A BOOK TITLE IS SUFFICIENT. ANY CODE OBIVOUSLY COPIED FROM OUTSIDE SOURCES WITH OUT A CITATION WILL EARN YOU NO CREDIT ON THIS PROBLEM. YOU ARE ALLOWED TO USE THESE RESOURCES ONLY ON THIS PART OF THIS PROBLEM!***

In [92]:
#Your code here
df.drop(columns='date',inplace=True)
df.dropna()

      year      state      month  number
0     1998       Acre    Janeiro     0.0
1     1999       Acre    Janeiro     0.0
2     2000       Acre    Janeiro     0.0
3     2001       Acre    Janeiro     0.0
4     2002       Acre    Janeiro     0.0
5     2003       Acre    Janeiro    10.0
6     2004       Acre    Janeiro     0.0
7     2005       Acre    Janeiro    12.0
8     2006       Acre    Janeiro     4.0
9     2007       Acre    Janeiro     0.0
10    2008       Acre    Janeiro     0.0
11    2009       Acre    Janeiro     0.0
12    2010       Acre    Janeiro     1.0
13    2011       Acre    Janeiro     0.0
14    2012       Acre    Janeiro     0.0
15    2013       Acre    Janeiro     0.0
16    2014       Acre    Janeiro     0.0
17    2015       Acre    Janeiro     1.0
18    2016       Acre    Janeiro    12.0
19    2017       Acre    Janeiro     0.0
20    1998       Acre  Fevereiro     0.0
21    1999       Acre  Fevereiro     0.0
22    2000       Acre  Fevereiro     0.0
23    2001       Acre  Fevereiro     0.0
24    2002       Acre  Fevereiro     1.0
25    2003       Acre  Fevereiro     0.0
26    2004       Acre  Fevereiro     3.0
27    2005       Acre  Fevereiro     0.0
28    2006       Acre  Fevereiro     0.0
29    2007       Acre  Fevereiro     5.0
...    ...        ...        ...     ...
6424  2007  Tocantins   Novembro   147.0
6425  2008  Tocantins   Novembro   104.0
6426  2009  Tocantins   Novembro   251.0
6427  2010  Tocantins   Novembro   283.0
6428  2011  Tocantins   Novembro   144.0
6429  2012  Tocantins   Novembro   179.0
6430  2013  Tocantins   Novembro   345.0
6431  2014  Tocantins   Novembro   451.0
6432  2015  Tocantins   Novembro   833.0
6433  2016  Tocantins   Novembro   623.0
6434  2017  Tocantins   Novembro   434.0
6435  1998  Tocantins   Dezembro     9.0
6436  1999  Tocantins   Dezembro    16.0
6437  2000  Tocantins   Dezembro    20.0
6438  2001  Tocantins   Dezembro    21.0
6439  2002  Tocantins   Dezembro    39.0
6440  2003  Tocantins   Dezembro   109.0
6441  2004  Tocantins   Dezembro    96.0
6442  2005  Tocantins   Dezembro    53.0
6443  2006  Tocantins   Dezembro    15.0
6444  2007  Tocantins   Dezembro    13.0
6445  2008  Tocantins   Dezembro     7.0
6446  2009  Tocantins   Dezembro    46.0
6447  2010  Tocantins   Dezembro    72.0
6448  2011  Tocantins   Dezembro   105.0
6449  2012  Tocantins   Dezembro   128.0
6450  2013  Tocantins   Dezembro    85.0
6451  2014  Tocantins   Dezembro   223.0
6452  2015  Tocantins   Dezembro   373.0
6453  2016  Tocantins   Dezembro   119.0

[6446 rows x 4 columns]

In [93]:
df_unique_month = list(df['month'].unique())
print(df_unique_month)
df['month']=df['month'].replace(['Janeiro'],'January')
df['month']=df['month'].replace(['Fevereiro'],'February')
df['month']=df['month'].replace(['Marï¿½o'],'March')
df['month']=df['month'].replace(['Abril'],'April')
df['month']=df['month'].replace(['Maio'],'May')
df['month']=df['month'].replace(['Junho'],'June')
df['month']=df['month'].replace(['Julho'],'July')
df['month']=df['month'].replace(['Agosto'],'August')
df['month']=df['month'].replace(['Setembro'],'September')
df['month']=df['month'].replace(['Outubro'],'October')
df['month']=df['month'].replace(['Novembro'],'November')
df['month']=df['month'].replace(['Dezembro'],'December')
df.head()

['Janeiro', 'Fevereiro', 'Marï¿½o', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro']

   year state    month  number
0  1998  Acre  January     0.0
1  1999  Acre  January     0.0
2  2000  Acre  January     0.0
3  2001  Acre  January     0.0
4  2002  Acre  January     0.0

In [94]:
df.loc[df["number"]< 0, "number"] = np.nan
df.loc[df["number"]> 50000, "number"] = np.nan

In [95]:
df_unique = list(df['year'].unique())
print(df_unique)

['1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '1000bc', '-40', '10bc', nan, "our new data scientist won't notice this"]

In [96]:
df = df[df.year != '1000bc']
df = df[df.year != '-40']
df = df[df.year != '10bc']
df = df[df.year != "our new data scientist won't notice this"]

In [97]:
df = df[df.year != '20/8']
df = df[df.year != '3.454/1']
df = df[df.year != '']
df = df[df.year.notnull()]
df = df[df.number.notnull()]
df = df[df.state.notnull()]
df = df[df.month.notnull()]

6438 rows are left

**Part B:** Extract the median number of forest fires per month, yearly, by state. Store these median values in the given python dictionary.

For Example:

If one year of one state had the following numbers of fires:

Jan: 1

Feb: 2

Mar: 3

Apr: 4

May: 5

Jun: 6

Jul: 7

Aug: 8

Sep: 9

Oct: 10

Nov: 11

Dec: 12

Then the median number of forest fires per month would be 6.5 (the average of the two middle elements since this has an even length)

If the state of "test" had 5 years of recorded data, with the following median forest fire values: \[1, 2, 7, 9, 3\],  then python dictionary should look like: 

\{

    "test": [1, 2, 7, 9, 3]
    
\}

Below we've given you one of the states values in a test, so you can ensure you are calculating the medians correctly.

In [102]:
#GIVEN DICTIONARY CODE
median_num_fires_monthly_yearly = {
    'Acre': None,
    'Alagoas': None,
    'Amapa': None,
    'Amazonas': None,
    'Bahia': None,
    'Ceara': None,
    'Distrito Federal': None,
    'Espirito Santo': None,
    'Goias': None,
    'Maranhao': None,
    'Mato Grosso': None,
    'Minas Gerais': None,
    'Para': None,
    'Paraiba': None,
    'Pernambuco': None,
    'Piau': None,
    'Rio': None,
    'Rondonia': None,
    'Roraima': None,
    'Santa Catarina': None,
    'Sao Paulo': None,
    'Sergipe': None,
    'Tocantins': None  
}

In [103]:
# Your code here
df_unique_area = list(df['state'].unique())
for a in df_unique_area:
    l = []
    df1 =  df[df.state == a]
    df_unique_year = list(df1['year'].unique())
    for d in df_unique_year:
        df2 = df1[df.year == d]
        var = df2.loc[:,"number"].median()
        l.append(var)
    median_num_fires_monthly_yearly[a]=l

C:\Users\singa\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

In [104]:
#Given Test
assert median_num_fires_monthly_yearly['Acre'] == \
[1.5, 0.0, 1.0, 0.5, 1.0, 8.0, 7.0, 13.0, 6.0, 4.5, 0.0, 2.5, 6.0, 7.0, 5.0, 13.5, 12.0, 24.0, 33.5, 45.0] \
, "something is wrong here"

In [106]:
#DONT CHANGE THIS. WE USE IT TO MAKE THE OUTPUT LEGIBLE FOR GRADING
import pprint
pp = pprint.PrettyPrinter(indent=1)
pp.pprint(median_num_fires_monthly_yearly)

{'Acre': [1.5,
          0.0,
          1.0,
          0.5,
          1.0,
          8.0,
          7.0,
          13.0,
          6.0,
          4.5,
          0.0,
          2.5,
          6.0,
          7.0,
          5.0,
          13.5,
          12.0,
          24.0,
          33.5,
          45.0],
 'Alagoas': [0.0,
             4.0,
             7.5,
             3.0,
             13.0,
             12.5,
             6.5,
             11.5,
             8.0,
             4.5,
             18.0,
             21.5,
             10.5,
             20.0,
             24.5,
             14.5,
             12.5,
             36.0,
             13.5,
             8.5],
 'Amapa': [0.0,
           1.5,
           1.0,
           0.5,
           5.0,
           8.0,
           7.0,
           3.0,
           4.0,
           0.0,
           2.0,
           4.0,
           2.0,
           4.0,
           13.0,
           2.5,
           7.0,
           9.5,
           12.0,
           3.0],
 'Amazonas': [4.0,
              9.0,
              55.5,
              8.5,
              30.5,
              152.5,
              107.5,
              61.0,
              21.5,
              63.5,
              24.0,
              57.5,
              119.5,
              87.0,
              62.5,
              138.0,
              138.0,
              231.5,
              433.0,
              119.0],
 'Bahia': [52.0,
           95.0,
           92.5,
           129.5,
           376.5,
           407.5,
           299.5,
           240.0,
           227.0,
           321.5,
           253.0,
           278.5,
           261.5,
           209.5,
           400.0,
           259.5,
           233.5,
           281.0,
           376.5,
           174.0],
 'Ceara': [38.5,
           65.0,
           17.0,
           113.5,
           54.0,
           61.5,
           22.5,
           38.0,
           36.5,
           96.5,
           22.0,
           17.0,
           132.5,
           25.0,
           161.5,
           40.5,
           81.0,
           76.0,
           112.0,
           26.0],
 'Distrito Federal': [0.0,
                      1.5,
                      0.5,
                      0.5,
                      1.0,
                      0.5,
                      3.5,
                      2.0,
                      0.5,
                      2.5,
                      3.0,
                      2.0,
                      7.0,
                      1.5,
                      2.0,
                      2.0,
                      4.0,
                      1.5,
                      7.0,
                      6.0],
 'Espirito Santo': [4.5,
                    9.5,
                    5.0,
                    6.5,
                    10.5,
                    24.5,
                    4.5,
                    5.0,
                    10.5,
                    11.0,
                    6.5,
                    12.5,
                    8.5,
                    6.5,
                    22.5,
                    15.5,
                    17.5,
                    47.5,
                    48.5,
                    10.0],
 'Goias': [30.0,
           180.0,
           42.0,
           67.0,
           181.5,
           148.5,
           224.0,
           154.0,
           77.5,
           86.5,
           48.0,
           96.5,
           172.0,
           103.5,
           98.0,
           166.5,
           195.5,
           228.0,
           200.0,
           135.0],
 'Maranhao': [176.0,
              156.0,
              163.5,
              324.5,
              750.5,
              769.5,
              1036.0,
              840.5,
              366.5,
              657.5,
              368.5,
              259.5,
              1148.5,
              813.0,
              620.5,
              804.5,
              1440.0,
              1264.5,
              1143.0,
              885.0],
 'Mato Grosso': [91.0,
                 518.5,
                 217.0,
                 279.0,
                 935.0,
                 744.0,
                 636.0,
                 543.0,
                 289.0,
                 256.0,
                 185.0,
                 477.5,
                 601.0,
                 388.0,
                 457.5,
                 400.5,
                 340.0,
                 595.5,
                 984.0,
                 702.0],
 'Minas Gerais': [26.5,
                  122.0,
                  58.0,
                  72.5,
                  216.0,
                  235.0,
                  167.0,
                  134.0,
                  84.5,
                  169.5,
                  99.0,
                  150.5,
                  147.0,
                  152.0,
                  204.0,
                  147.0,
                  300.0,
                  244.0,
                  207.0,
                  136.0],
 'Para': [638.0,
          766.0,
          303.5,
          375.0,
          460.5,
          1235.5,
          4436.0,
          1631.5,
          509.0,
          471.5,
          407.5,
          319.0,
          934.5,
          370.0,
          526.5,
          173.0,
          572.0,
          815.5,
          1450.5,
          679.0],
 'Paraiba': [34.5,
             50.0,
             38.5,
             63.0,
             105.0,
             75.5,
             80.5,
             60.0,
             27.0,
             40.0,
             46.0,
             39.0,
             46.5,
             58.0,
             45.0,
             65.0,
             56.5,
             67.5,
             49.0,
             3.0],
 'Pernambuco': [3.0,
                14.5,
                10.5,
                6.5,
                21.5,
                30.5,
                21.0,
                39.0,
                29.5,
                20.5,
                40.0,
                21.5,
                40.0,
                33.0,
                55.0,
                34.5,
                30.5,
                44.0,
                21.5,
                20.0],
 'Piau': [82.5,
          60.5,
          50.0,
          158.5,
          267.0,
          247.5,
          401.5,
          308.0,
          141.5,
          310.0,
          79.0,
          190.5,
          294.0,
          412.0,
          390.5,
          312.0,
          359.5,
          454.5,
          263.5,
          193.0],
 'Rio': [1.0,
         17.5,
         10.5,
         13.0,
         15.0,
         28.5,
         45.5,
         35.5,
         22.5,
         13.0,
         18.0,
         29.5,
         23.5,
         28.5,
         41.0,
         24.5,
         50.0,
         43.5,
         37.0,
         43.0],
 'Rondonia': [14.5,
              9.0,
              13.0,
              18.0,
              116.0,
              144.0,
              179.5,
              126.0,
              28.5,
              43.0,
              9.5,
              15.0,
              101.0,
              92.0,
              41.0,
              65.5,
              118.0,
              200.5,
              159.0,
              192.0],
 'Roraima': [0.0,
             12.5,
             15.0,
             44.5,
             90.5,
             20.5,
             94.0,
             71.5,
             55.0,
             12.0,
             28.0,
             135.0,
             22.5,
             78.0,
             72.5,
             62.5,
             105.0,
             172.0,
             86.0,
             51.0],
 'Santa Catarina': [0.0,
                    9.0,
                    20.0,
                    8.0,
                    32.0,
                    102.0,
                    83.5,
                    74.0,
                    43.0,
                    15.5,
                    29.0,
                    33.0,
                    21.0,
                    25.0,
                    42.0,
                    60.5,
                    44.0,
                    34.5,
                    54.5,
                    51.0],
 'Sao Paulo': [277.5,
               449.0,
               201.0,
               189.5,
               240.0,
               134.5,
               123.0,
               187.5,
               92.5,
               92.5,
               56.0,
               75.0,
               146.5,
               111.5,
               82.0,
               113.5,
               146.5,
               98.0,
               182.5,
               107.0],
 'Sergipe': [0.0,
             1.5,
             0.0,
             1.5,
             4.0,
             2.5,
             7.5,

             9.5,
             4.0,
             1.5,
             1.0,
             5.5,
             1.0,
             4.5,
             11.5,
             5.0,
             5.5,
             23.0,
             9.5,
             1.0],
 'Tocantins': [5.0,
               32.5,
               82.5,
               74.0,
               172.5,
               127.5,
               387.0,
               253.5,
               99.5,
               198.5,
               92.5,
               171.0,
               499.5,
               249.0,
               346.5,
               359.0,
               337.0,
               672.5,
               700.5,
               576.0]}

**Part C:** Since we cannot rely on the central limit thereom for the median, we'll bootstrap some samples. Bootstrap 1000 samples for each state. Each bootstrapped sample should have 50 values drawn from the original sample.

Find the median of each bootstrapped sample, and add it to a list. Save the list of median values for the states of **Sao Paulo** and **Goias**. We'll use them later to plot in part D. Then determine the 95% confidence interval of the true median from each list of bootstrapped medians for each state. Add a list of the low and high values of the confidence interval to the given python dictionary below. To help you check your work, the confidence interval of the state of Acre should be from roughly 4 to 7. Your values will change though, because each bootstrapped sample is picked randomly from the original.

For Example:

If the 95% confidence interval on the median is from 6 to 22 for the state of "test", then the dictionary would look like:

{

    "test": [6, 22]
    
}

In [108]:
#GIVEN CODE
median_num_fires_bootstrap = {
    'Acre': None,
    'Alagoas': None,
    'Amapa': None,
    'Amazonas': None,
    'Bahia': None,
    'Ceara': None,
    'Distrito Federal': None,
    'Espirito Santo': None,
    'Goias': None,
    'Maranhao': None,
    'Mato Grosso': None,
    'Minas Gerais': None,
    'Para': None,
    'Paraiba': None,
    'Pernambuco': None,
    'Piau': None,
    'Rio': None,
    'Rondonia': None,
    'Roraima': None,
    'Santa Catarina': None,
    'Sao Paulo': None,
    'Sergipe': None,
    'Tocantins': None  
}

In [160]:
#Your code here.
def median_confidence_interval(data, confidence=0.95):
    lower = 0
    upper = 0
    
    n = len(data)
    df5 = pd.DataFrame(np.array(data),dtype=np.int)
    m = df5.median()
    h =  stats.t.ppf((1 + confidence) / 2, n - 1)
    lower = m - h
    upper = m + h
    c=[lower,upper]
    return c
G = []
sp = []
for a in df_unique_area:
    l = []
    ci = []
    df1 =  median_num_fires_monthly_yearly[a]
    for i in range(0,1000):
        df4 = pd.DataFrame(np.array(df1))
        var = df4.sample(n=50,replace="True")
        var2=var.median()
        l.append(var2)
        if(a == "Goias"):
            G.append(var2)
        if(a == "Sao Paulo"):
            sp.append(var2)
    ci = median_confidence_interval(l)
    median_num_fires_bootstrap[a]=ci

In [161]:
#DONT CHANGE THIS. WE USE IT TO MAKE THE OUTPUT LEGIBLE FOR GRADING
import pprint
pp = pprint.PrettyPrinter(indent=1)
pp.pprint(median_num_fires_bootstrap)

{'Acre': [0    4.037659
dtype: float64, 0    7.962341
dtype: float64],
 'Alagoas': [0    10.037659
dtype: float64, 0    13.962341
dtype: float64],
 'Amapa': [0    1.037659
dtype: float64, 0    4.962341
dtype: float64],
 'Amazonas': [0    61.037659
dtype: float64, 0    64.962341
dtype: float64],
 'Bahia': [0    254.037659
dtype: float64, 0    257.962341
dtype: float64],
 'Ceara': [0    45.037659
dtype: float64, 0    48.962341
dtype: float64],
 'Distrito Federal': [0    0.037659
dtype: float64,
                      0    3.962341
dtype: float64],
 'Espirito Santo': [0    8.037659
dtype: float64,
                    0    11.962341
dtype: float64],
 'Goias': [0    139.037659
dtype: float64, 0    142.962341
dtype: float64],
 'Maranhao': [0    758.037659
dtype: float64, 0    761.962341
dtype: float64],
 'Mato Grosso': [0    465.037659
dtype: float64,
                 0    468.962341
dtype: float64],
 'Minas Gerais': [0    146.037659
dtype: float64,
                  0    149.962341
dtype: float64],
 'Para': [0    547.037659
dtype: float64, 0    550.962341
dtype: float64],
 'Paraiba': [0    47.037659
dtype: float64, 0    50.962341
dtype: float64],
 'Pernambuco': [0    23.037659
dtype: float64, 0    26.962341
dtype: float64],
 'Piau': [0    263.037659
dtype: float64, 0    266.962341
dtype: float64],
 'Rio': [0    24.037659
dtype: float64, 0    27.962341
dtype: float64],
 'Rondonia': [0    76.037659
dtype: float64, 0    79.962341
dtype: float64],
 'Roraima': [0    56.037659
dtype: float64, 0    59.962341
dtype: float64],
 'Santa Catarina': [0    31.037659
dtype: float64,
                    0    34.962341
dtype: float64],
 'Sao Paulo': [0    126.037659
dtype: float64, 0    129.962341
dtype: float64],
 'Sergipe': [0    2.037659
dtype: float64, 0    5.962341
dtype: float64],
 'Tocantins': [0    221.037659
dtype: float64, 0    224.962341
dtype: float64]}

**Part D:** Plot a histogram of the frequency of different median values for the two states **Sao Paulo** and **Goias**. Overlay these histograms on the same plot. Include axis labels, a title, a legend, etc. Choose two colors that work well together and provide enough contrast (e.g. No one can see gold overlayed with yellow), and use reasonable values of the **alpha** parameter so you can see both histograms. Plot two vertical lines that represent the outer bounds of the 95% confidence interval on the true median for each state, in the same color as the state. Does the data for the median look normally distributed? Why or why not? Does this validate our decision to not use the central limit theorem and instead bootstrap our median samples? Explain in a markdown cell below.

In [ ]:
print(G)

In [ ]:
#Your code here.
v3 = 142.962341
v4 = 129.962341
fig, ax = plt.subplots(figsize=(12,6))
ax.hist(G,facecolor="coral", edgecolor="white", alpha=0.5, bins=25, label="Goias", density=True)
ax.hist(sp,facecolor="seagreen", edgecolor="white", alpha=0.5, bins=20,label="Sao Paulo", density=True)
ax.set_xlabel("Median Forest Fires", fontsize=16)
ax.set_ylabel("Frequency", fontsize=16)
ax.set_title("Median Forest Fires per Month for Goias and Sao Paulo", fontsize=24)
#ax.axvline(v3, color='coral', linestyle='solid', linewidth=1,label="Goias")
#ax.axvline(v4, color='seagreen', linestyle='solid', linewidth=1,label="Sao Paulo")
ax.grid(alpha=0.5)
ax.set_axisbelow(True)
ax.legend();

<br>

---
<a id='p2'></a>
[Back to top](#top)

### [40 points] Problem 2:  Sharknado Prediction

Governor Hickenlooper has charged you with the task of assessing the factors associated with sharknado risk in Colorado. As everyone knows, sharknadoes are a leading cause of sharknado-related illness, and you are a world-renowned data/shark scientist.

You decide to use multiple linear regression to understand and predict what factors lead to increased sharknado hazard. Your lead scientist, aptly named Fin, has collected lots of relevant data at a local sharknado hotspot, the Boulder Reservoir[\*](#footnote). The data cover a variety of sharknado-related environmental and other conditions, and you'll find this data in the file `sharknadoes.csv`. 

**Response**: 

- $\texttt{sharknado hazard}$: the hazard of a sharknado, where 1 is very unlikely and 100 is highly likely

**Features**: 

- $\texttt{taunts}$: the number of times over the past year that someone has taunted a shark
- $\texttt{clouds}$: what percentage of the sky was covered by clouds (fraction, 0-1)
- $\texttt{precipitation}$: amount of precipitation in the past 72 hours (inches)
- $\texttt{earthquake}$: the intensity of the most recent earthquake measured in the continental United States
- $\texttt{shark attacks}$: the number of shark attacks within 72 hours prior to the observation
- $\texttt{ice cream sold}$: the number of units of ice cream sold at the beach concession stand 
- $\texttt{misery index}$: an economic indicator for how miserable the average United States citizen is, based on the unemployment rate and the inflation rate. More [here](https://www.stuffyoushouldknow.com/podcasts/whats-the-misery-index.htm) and [here](https://en.wikipedia.org/wiki/Misery_index_(economics)). Higher values correspond to more miserable citizens.
- $\texttt{temperature}$: the outside temperature, measured in degrees Fahrenheit
- $\texttt{humidity}$: relative humidity (percent, 0-100)
- $\texttt{pizzas sold}$: the number of pizzas sold at the beach concession stand in the past year
- $\texttt{pressure}$: local air pressure (millibar) 
- $\texttt{octopuses}$: the number of octupuses in the vicinity on the day of the observation
- $\texttt{Zach's shoe size}$: the size of the shoes Zach was wearing when the observation was made
- $\texttt{Rachel's shoe size}$: the size of the shoes Rachel was wearing when the observation was made

**Part A**: Read the data from `sharknadoes.csv` into a Pandas DataFrame.  Note that since we will be doing a multiple linear regression we will need all of the features. To make sure the data is "clean", drop any row in the DataFrame that is missing data.

In [1]:
#Your code here.

**Part B**: Perform the appropriate statistical test at the $\alpha = 0.025$ significance level to determine if _at least one_ of the features is related to the the response $y$.  Clearly describe your methodology and show all computations in Python.

In [ ]:
#Your code here.

**Part C**: Write a function `backward_select(df, resp_str, maxsse)` that takes in the DataFrame (`df`), the name of the column corresponding to the response (`resp_str`), and the maximum desired sum of squared errors (`maxsse`), and returns a list of feature names corresponding to the most important features via backward selection.  Use your code to determine the reduced MLR model with the minimal number of features such that the SSE of the reduced model is less than 570. At each stage in backward selection you should remove the feature that has the highest p-value associated with the hypothesis test for the given slope coefficient $\beta_k \neq 0$.

Your code should clearly indicate which feature was removed in each stage, and the SSE associated with the model fit before the feature's removal. _Specifically, please write your code to print the name of the feature that is going to be removed and the SSE before its removal_. Afterward, be sure to report all of the retained features and the SSE of the reduced model.

**Note**: The point of this exercise is to see if you can implement **backward_select** yourself.  You may of course use canned routines like statmodels OLS, but you may not call any Python method that explicitly performs backward selection.

In [ ]:
def backward_select(df, resp_str, maxsse):
    #Your code here.

**Part D**: Write down the final multiple linear regression model, including estimated parameters, obtained by your backward selection process.

In [ ]:
#Your code here.

**Part E**: Perform the appropriate statistical test at the $\alpha = 0.025$ significance level to determine whether there is a statistically significant difference between the full model with all features and the reduced model obtained by backward selection in **Part D**. You may use output from your model fit above, but all calculations should be set up in Markdown/MathJax.

**Part F**: Based on your conclusions in **Part E**, use the _better_ of the two models to predict the sharknado hazard when the following features are observed: 

- $\texttt{taunts}$: 47
- $\texttt{clouds}$: 0.8
- $\texttt{precipitation}$: 1 inch
- $\texttt{earthquake}$: 5
- $\texttt{shark attacks}$: 11
- $\texttt{ice cream sold}$: 120
- $\texttt{misery index}$: 15
- $\texttt{temperature}$: 70 degrees F
- $\texttt{humidity}$: 83
- $\texttt{pizzas sold}$: 5500
- $\texttt{pressure}$: 850 millibar 
- $\texttt{octopuses}$: 6
- $\texttt{Zach's shoe size}$: 9.5
- $\texttt{Rachel's shoe size}$: 9

In [2]:
#Your code here.

**Part G:** Consider the model you used in Part E, and consider the fact that you are trying to predict **sharknado hazard**. What is one critical drawback to the MLR model (or any MLR model) for predicting shardnado hazard? What are some modifications that could improve on this issue?